### ISSUE TITLE
Cannot find a file

### ISSUE THREAD

**Issue by RubixDev** [Wyn-Price/CurseMaven#20]
For some reason `modImplementation 'curse.maven:carpet-shadow-581787:4614346'` doesn't work for me, even though it is exactly what the CurseForge site itself suggests: https://www.curseforge.com/minecraft/mc-mods/carpet-shadow/files/4614346. The `/test` request also succeeds (https://www.cursemaven.com/test/581787/4614346/), but the actual maven request fails (https://cursemaven.com/curse/maven/carpet-shadow-581787/4614346/carpet-shadow-581787-4614346.jar). Is it maybe because the actual filename has spaces in it?
This is the only occasion where I've had a problem with this service, it works great otherwise!

**Comment by SettingDust** [comment]
https://cursemaven.com/test/700485/4738904 failed too. Seems the `+` encoding to %20 causing that
https://www.cursemaven.com/curse/maven/libertys-villagers-700485/4738904/libertys-villagers-700485-4738904.jar

**Comment by TelepathicGrunt** [comment]
Also impact downloading embeddium due to the + involved. Embeddium has 3rd party on. The error in gradle says Forbidden.
![image](https://github.com/Wyn-Price/CurseMaven/assets/40846040/7fd13690-7f31-4d2f-9c7c-42267a3ee38d)
![image](https://github.com/Wyn-Price/CurseMaven/assets/40846040/6cfc857c-4ad8-4602-abf3-52900e074b2c)

**Comment by Wyn-Price** [comment]
@TelepathicGrunt it seems like it would most likely be due to the `+` in the filename. What version of gradle are you on.

Also, does the problem still exist when you use https://beta.cursemaven.com/?

**Comment by TelepathicGrunt** [comment]
I am using Gradle 8.1.1 for my workspace. Testing `https://beta.cursemaven.com` and it is breaking on PneumaticCraft despite that working with `https://www.cursemaven.com`.

```
A problem occurred configuring project ':forge'.
> Could not resolve all files for configuration ':forge:modCompileOnly'.
   > Could not download pneumaticcraft-281849-4792404.jar (curse.maven:pneumaticcraft-281849:4792404)
      > Could not get resource 'https://beta.cursemaven.com/curse/maven/pneumaticcraft-281849/4792404/pneumaticcraft-281849-4792404.jar'.
         > Could not HEAD 'https://beta.cursemaven.com/curse/maven/pneumaticcraft-281849/4792404/pneumaticcraft-281849-4792404.jar'. Received status code 500 from server: Internal Server Error

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

```

This is my project workspace: https://github.com/TelepathicGrunt/Bumblezone/tree/1.20-Arch

The outermost build.gradle is where the mavens lives. Then in Forge module's build.gradle, I was trying to import Embeddium as a runtime dependency.

**Comment by Wyn-Price** [comment]
That's very interesting that it works on the beta build but not the main. 

Traditionally, cursemaven has always had issues with gradle re-encoding the `+` incorrectly, leading to a broken link. The way this has been usually fixed is by opening a reverse proxy to `meda.forgecdn.net`. If you're intrested, you can find more info here: 
https://github.com/Wyn-Price/CurseMaven/blob/e1855564dc39c9bc92fb64ad6793e3be824b3359/src/util.ts#L13-L34

This has worked fine in the past, except due to a 5MB bandwidth limit on the deployment. This is why the pneumaticcraft failed, it's around 10MB.

Due to recent migrations to run on curseforge infrastructure, I've added a cloudflare worker "middleman" that fetches content from the actual server. Unknown to me, this worker actually follows the redirects, meaning that the we have have the cloudflare worker follow the redirect correcetly and download the entire content.

Another change curseforge made was to return the `%2b` in the filename, instead of the `+`, meaning the test to whether we should use `/download-binary/`was broken. I fixed this in https://github.com/Wyn-Price/CurseMaven/commit/0ba4ab5ef454d0e72e226d0494e4ec4cfe2a45c5, but that now re-broke downloading files over 5MB.

The good news is that I can just remove all of this entierly, as we can make the cloudflare worker follow the redirects instead of gradle.

**Comment by Wyn-Price** [comment]
@TelepathicGrunt are you able to re-try `beta`? It should work now - it appears to work for me

**Comment by TelepathicGrunt** [comment]
Yep the beta now works for pneumaticcraft and embeddium

**Comment by eve0415** [comment]
I am also getting `Forbidden` when trying with <https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing/files/4709710>. Tried <https://beta.cursemaven.com/test/266515/4709710> and <https://www.cursemaven.com/test/266515/4709710>

**Comment by Wyn-Price** [comment]
Does the mod have 3rd part downloads disabled?

**Comment by eve0415** [comment]
maybe? how do i know?

**Comment by Wyn-Price** [comment]
Sorry for the delay @eve0415, but `https://beta.cursemaven.com/curse/maven/if-266515/4709710/if-266515-4709710.jar` appears to work. The URL you sent before was for `curseforge.com`. If you are still having issues, please open a new issue
